"use client";

import PageFooter from "@/components/page-footer";
import PageHeader from "@/components/page-header";
// import { useEffect } from "react";

import "bootstrap/dist/css/bootstrap.css";
import "../globals.css";

// export const metadata = {
//   title: "Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   require("bootstrap/dist/js/bootstrap.bundle");
  // }, []);
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        // {/* <PageHeader /> */}
        <div className="container-fluid">
          <div className="row auth">
            <div className="col-lg-6">
              <img
                className="img-fluid"
                src="https://images.unsplash.com/photo-1558981403-c5f9899a28bc"
                alt="Image"
              />
            </div>
            <div className="col-lg-6">{children}</div>
          </div>
        </div>
        {/* <PageFooter /> */}
      </body>
    </html>
  );
}
